update_config:
  enabled: true
  update_branch_format: version-update/{0}
  labels:
    - version-update
  pr_reviewers:
    - folio-org/kitfox
    - folio-org/thor

  ruleset:
    enabled: true
    pattern: "{0}-eureka-ci"
    required_checks:
      - context: "eureka-ci / validate-application"
    merge_queue:
      enabled: true
      check_response_timeout_minutes: 60
      grouping_strategy: "ALLGREEN"
      max_entries_to_build: 5
      max_entries_to_merge: 5
      merge_method: "SQUASH"
      min_entries_to_merge: 1
      min_entries_to_merge_wait_minutes: 5
    bypass_actors:
      - actor_type: "Integration"
        bypass_mode: "always"

branches:
  - snapshot:
      enabled: true
      need_pr: false
      pre_release: "only"
      descriptor_build_offset: "100200000000000"
      ruleset:
        enabled: false
#  - R2-2024:
#      enable: false
#      need_pr: true
#      pre_release: "false"
